ALTER TABLE player_dungeon_runs
  ADD COLUMN IF NOT EXISTS awaiting_option BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS option_floor INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS refresh_count INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS current_options JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS selected_buffs JSONB NOT NULL DEFAULT '[]'::jsonb;
