package service

var achievementCategoryOrder = []string{
	"equipment",
	"dungeon_explore",
	"dungeon_combat",
	"cultivation",
	"breakthrough",
	"exploration",
	"collection",
	"resources",
	"alchemy",
}

var achievementCategoryNames = map[string]string{
	"equipment":       "装备成就",
	"dungeon_explore": "秘境探索",
	"dungeon_combat":  "秘境战斗",
	"cultivation":     "修炼成就",
	"breakthrough":    "突破成就",
	"exploration":     "探索成就",
	"collection":      "收集成就",
	"resources":       "资源成就",
	"alchemy":         "炼丹成就",
}

var achievementDefinitions = []achievementDefinition{
	{
		Category:    "equipment",
		ID:          "equipment_1",
		Name:        "初获装备",
		Description: "获得第一件装备",
		Reward:      achievementReward{Spirit: 200},
	},
	{
		Category:    "equipment",
		ID:          "equipment_2",
		Name:        "装备收藏",
		Description: "拥有10件装备",
		Reward:      achievementReward{Spirit: 1000},
	},
	{
		Category:    "equipment",
		ID:          "equipment_3",
		Name:        "装备大师",
		Description: "拥有一件极品品质装备",
		Reward:      achievementReward{Spirit: 3000},
	},
	{
		Category:    "equipment",
		ID:          "equipment_4",
		Name:        "炼器宗师",
		Description: "强化任意装备到+10",
		Reward:      achievementReward{Spirit: 5000},
	},
	{
		Category:    "equipment",
		ID:          "equipment_5",
		Name:        "装备之王",
		Description: "拥有一套完整的极品装备",
		Reward:      achievementReward{Spirit: 10000},
	},
	{
		Category:    "equipment",
		ID:          "equipment_6",
		Name:        "炼器新秀",
		Description: "初次强化装备",
		Reward:      achievementReward{Spirit: 500},
	},
	{
		Category:    "equipment",
		ID:          "equipment_7",
		Name:        "装备鉴赏家",
		Description: "拥有20件不同部位的装备",
		Reward:      achievementReward{Spirit: 2000},
	},
	{
		Category:    "equipment",
		ID:          "equipment_8",
		Name:        "神装收集者",
		Description: "拥有5件仙品装备",
		Reward:      achievementReward{Spirit: 10000},
	},
	{
		Category:    "equipment",
		ID:          "equipment_9",
		Name:        "强化大师",
		Description: "将一件装备强化到+15",
		Reward:      achievementReward{Spirit: 20000},
	},
	{
		Category:    "equipment",
		ID:          "equipment_10",
		Name:        "全能装备师",
		Description: "拥有每部位一件仙品装备",
		Reward:      achievementReward{Spirit: 50000},
	},
	{
		Category:    "dungeon_explore",
		ID:          "dungeon_1",
		Name:        "初探秘境",
		Description: "首次进入秘境",
		Reward:      achievementReward{Spirit: 200},
	},
	{
		Category:    "dungeon_explore",
		ID:          "dungeon_2",
		Name:        "秘境先驱者",
		Description: "通过第5层秘境",
		Reward:      achievementReward{Spirit: 500},
	},
	{
		Category:    "dungeon_explore",
		ID:          "dungeon_3",
		Name:        "秘境探索者",
		Description: "通过第10层秘境",
		Reward:      achievementReward{Spirit: 1000},
	},
	{
		Category:    "dungeon_explore",
		ID:          "dungeon_4",
		Name:        "秘境探险家",
		Description: "通过第20层秘境",
		Reward:      achievementReward{Spirit: 2000},
	},
	{
		Category:    "dungeon_explore",
		ID:          "dungeon_5",
		Name:        "秘境猎手",
		Description: "通过第30层秘境",
		Reward:      achievementReward{Spirit: 5000},
	},
	{
		Category:    "dungeon_explore",
		ID:          "dungeon_6",
		Name:        "秘境征服者",
		Description: "通过第50层秘境",
		Reward:      achievementReward{Spirit: 5000},
	},
	{
		Category:    "dungeon_explore",
		ID:          "dungeon_7",
		Name:        "秘境征服者",
		Description: "通过第75层秘境",
		Reward:      achievementReward{Spirit: 15000},
	},
	{
		Category:    "dungeon_explore",
		ID:          "dungeon_8",
		Name:        "秘境王者",
		Description: "通过第100层秘境",
		Reward:      achievementReward{Spirit: 20000},
	},
	{
		Category:    "dungeon_explore",
		ID:          "dungeon_9",
		Name:        "秘境传奇",
		Description: "通过第150层秘境",
		Reward:      achievementReward{Spirit: 30000},
	},
	{
		Category:    "dungeon_explore",
		ID:          "dungeon_10",
		Name:        "秘境之主",
		Description: "通过第200层秘境",
		Reward:      achievementReward{Spirit: 50000},
	},
	{
		Category:    "dungeon_combat",
		ID:          "dungeon_combat_1",
		Name:        "初战告捷",
		Description: "击杀10个普通敌人",
		Reward:      achievementReward{Spirit: 500},
	},
	{
		Category:    "dungeon_combat",
		ID:          "dungeon_combat_2",
		Name:        "战无不胜",
		Description: "击杀50个普通敌人",
		Reward:      achievementReward{Spirit: 2000},
	},
	{
		Category:    "dungeon_combat",
		ID:          "dungeon_combat_3",
		Name:        "百战不殆",
		Description: "击杀100个普通敌人",
		Reward:      achievementReward{Spirit: 2000},
	},
	{
		Category:    "dungeon_combat",
		ID:          "dungeon_combat_4",
		Name:        "收割者",
		Description: "击杀500个普通敌人",
		Reward:      achievementReward{Spirit: 3000},
	},
	{
		Category:    "dungeon_combat",
		ID:          "dungeon_combat_5",
		Name:        "精英猎手",
		Description: "击杀50个精英敌人",
		Reward:      achievementReward{Spirit: 5000},
	},
	{
		Category:    "dungeon_combat",
		ID:          "dungeon_combat_6",
		Name:        "BOSS终结者",
		Description: "击杀10个BOSS",
		Reward:      achievementReward{Spirit: 10000},
	},
	{
		Category:    "dungeon_combat",
		ID:          "dungeon_combat_7",
		Name:        "BOSS猎人",
		Description: "击杀50个BOSS",
		Reward:      achievementReward{Spirit: 10000},
	},
	{
		Category:    "dungeon_combat",
		ID:          "dungeon_combat_8",
		Name:        "秘境终结者",
		Description: "击杀100个BOSS",
		Reward:      achievementReward{Spirit: 20000},
	},
	{
		Category:    "dungeon_combat",
		ID:          "dungeon_combat_9",
		Name:        "无敌战神",
		Description: "总击杀数达到1000",
		Reward:      achievementReward{Spirit: 30000},
	},
	{
		Category:    "dungeon_combat",
		ID:          "dungeon_combat_10",
		Name:        "无尽战神",
		Description: "总击杀数达到10000",
		Reward:      achievementReward{Spirit: 50000},
	},
	{
		Category:    "cultivation",
		ID:          "cultivation_1",
		Name:        "初入修仙",
		Description: "开始踏上修仙之路",
		Reward:      achievementReward{Spirit: 100},
	},
	{
		Category:    "cultivation",
		ID:          "cultivation_2",
		Name:        "修炼入门",
		Description: "累计修炼时间达到30分钟",
		Reward:      achievementReward{Spirit: 300},
	},
	{
		Category:    "cultivation",
		ID:          "cultivation_3",
		Name:        "勤修苦练",
		Description: "累计修炼时间达到1小时",
		Reward:      achievementReward{Spirit: 500},
	},
	{
		Category:    "cultivation",
		ID:          "cultivation_4",
		Name:        "修炼小有所成",
		Description: "累计修炼时间达到12小时",
		Reward:      achievementReward{Spirit: 1000},
	},
	{
		Category:    "cultivation",
		ID:          "cultivation_5",
		Name:        "修炼狂人",
		Description: "累计修炼时间达到48小时",
		Reward:      achievementReward{Spirit: 3000},
	},
	{
		Category:    "cultivation",
		ID:          "cultivation_6",
		Name:        "修炼成痴",
		Description: "累计修炼时间达到24小时",
		Reward:      achievementReward{Spirit: 2000},
	},
	{
		Category:    "cultivation",
		ID:          "cultivation_7",
		Name:        "道心稳固",
		Description: "累计修炼时间达到7天",
		Reward:      achievementReward{Spirit: 5000, SpiritRate: 1.1},
	},
	{
		Category:    "cultivation",
		ID:          "cultivation_8",
		Name:        "修炼大成",
		Description: "累计修炼时间达到15天",
		Reward:      achievementReward{Spirit: 10000, SpiritRate: 1.2},
	},
	{
		Category:    "cultivation",
		ID:          "cultivation_9",
		Name:        "修仙百年",
		Description: "累计修炼时间达到30天",
		Reward:      achievementReward{Spirit: 10000, SpiritRate: 1.3},
	},
	{
		Category:    "cultivation",
		ID:          "cultivation_10",
		Name:        "修炼至尊",
		Description: "累计修炼时间达到100天",
		Reward:      achievementReward{Spirit: 50000, SpiritRate: 2},
	},
	{
		Category:    "breakthrough",
		ID:          "breakthrough_1",
		Name:        "初窥门径",
		Description: "首次突破",
		Reward:      achievementReward{Spirit: 200},
	},
	{
		Category:    "breakthrough",
		ID:          "breakthrough_2",
		Name:        "突破新秀",
		Description: "首次突破成功",
		Reward:      achievementReward{Spirit: 500},
	},
	{
		Category:    "breakthrough",
		ID:          "breakthrough_3",
		Name:        "修炼有成",
		Description: "突破次数达到10次",
		Reward:      achievementReward{Spirit: 1000},
	},
	{
		Category:    "breakthrough",
		ID:          "breakthrough_4",
		Name:        "道法自然",
		Description: "突破次数达到50次",
		Reward:      achievementReward{Spirit: 5000},
	},
	{
		Category:    "breakthrough",
		ID:          "breakthrough_5",
		Name:        "登峰造极",
		Description: "突破次数达到100次",
		Reward:      achievementReward{Spirit: 10000, SpiritRate: 1.2},
	},
	{
		Category:    "breakthrough",
		ID:          "breakthrough_6",
		Name:        "问鼎巅峰",
		Description: "达到化神境界",
		Reward:      achievementReward{Spirit: 50000, SpiritRate: 1},
	},
	{
		Category:    "breakthrough",
		ID:          "breakthrough_7",
		Name:        "突破达人",
		Description: "达到返虚境界",
		Reward:      achievementReward{Spirit: 100000, SpiritRate: 1.2},
	},
	{
		Category:    "breakthrough",
		ID:          "breakthrough_8",
		Name:        "突破宗师",
		Description: "达到大乘境界",
		Reward:      achievementReward{Spirit: 200000, SpiritRate: 1.5},
	},
	{
		Category:    "breakthrough",
		ID:          "breakthrough_9",
		Name:        "突破至尊",
		Description: "达到仙人境界",
		Reward:      achievementReward{Spirit: 300000, SpiritRate: 1.7},
	},
	{
		Category:    "breakthrough",
		ID:          "breakthrough_10",
		Name:        "突破之神",
		Description: "达到大罗境界",
		Reward:      achievementReward{Spirit: 500000, SpiritRate: 2},
	},
	{
		Category:    "exploration",
		ID:          "exploration_1",
		Name:        "初探世界",
		Description: "首次进行探索",
		Reward:      achievementReward{Spirit: 100},
	},
	{
		Category:    "exploration",
		ID:          "exploration_2",
		Name:        "探索新秀",
		Description: "探索次数达到10次",
		Reward:      achievementReward{Spirit: 300},
	},
	{
		Category:    "exploration",
		ID:          "exploration_3",
		Name:        "探索达人",
		Description: "探索次数达到50次",
		Reward:      achievementReward{Spirit: 1000},
	},
	{
		Category:    "exploration",
		ID:          "exploration_4",
		Name:        "四处游历",
		Description: "探索次数达到100次",
		Reward:      achievementReward{Spirit: 1000},
	},
	{
		Category:    "exploration",
		ID:          "exploration_5",
		Name:        "探索大师",
		Description: "探索次数达到200次",
		Reward:      achievementReward{Spirit: 5000},
	},
	{
		Category:    "exploration",
		ID:          "exploration_6",
		Name:        "探索传奇",
		Description: "探索次数达到500次",
		Reward:      achievementReward{Spirit: 15000},
	},
	{
		Category:    "exploration",
		ID:          "exploration_7",
		Name:        "游历天下",
		Description: "探索次数达到1000次",
		Reward:      achievementReward{Spirit: 5000},
	},
	{
		Category:    "exploration",
		ID:          "exploration_8",
		Name:        "寻宝达人",
		Description: "获得100件物品",
		Reward:      achievementReward{Spirit: 2000},
	},
	{
		Category:    "exploration",
		ID:          "exploration_9",
		Name:        "机缘深厚",
		Description: "触发100次随机事件",
		Reward:      achievementReward{Spirit: 3000, Luck: 1.1},
	},
	{
		Category:    "exploration",
		ID:          "exploration_10",
		Name:        "探索之神",
		Description: "触发500次随机事件",
		Reward:      achievementReward{Spirit: 30000, Luck: 1.5},
	},
	{
		Category:    "collection",
		ID:          "collection_1",
		Name:        "初识灵草",
		Description: "收集首株灵草",
		Reward:      achievementReward{Spirit: 100},
	},
	{
		Category:    "collection",
		ID:          "collection_2",
		Name:        "灵草学徒",
		Description: "收集5种不同灵草",
		Reward:      achievementReward{Spirit: 500},
	},
	{
		Category:    "collection",
		ID:          "collection_3",
		Name:        "灵草收藏家",
		Description: "收集10种不同灵草",
		Reward:      achievementReward{Spirit: 1000},
	},
	{
		Category:    "collection",
		ID:          "collection_4",
		Name:        "灵草猎人",
		Description: "收集50株灵草",
		Reward:      achievementReward{Spirit: 2000, HerbRate: 1},
	},
	{
		Category:    "collection",
		ID:          "collection_5",
		Name:        "灵草园主",
		Description: "拥有100株灵草",
		Reward:      achievementReward{Spirit: 5000, HerbRate: 1.5},
	},
	{
		Category:    "collection",
		ID:          "collection_6",
		Name:        "灵草之巅",
		Description: "收集200株灵草",
		Reward:      achievementReward{Spirit: 30000, HerbRate: 2},
	},
	{
		Category:    "collection",
		ID:          "collection_7",
		Name:        "仙品收藏",
		Description: "收集100个稀有灵草",
		Reward:      achievementReward{Spirit: 2000, HerbRate: 1},
	},
	{
		Category:    "collection",
		ID:          "collection_8",
		Name:        "灵草大师",
		Description: "收集100株极品灵草",
		Reward:      achievementReward{Spirit: 5000, HerbRate: 1.3},
	},
	{
		Category:    "collection",
		ID:          "collection_9",
		Name:        "仙草收集者",
		Description: "收集100株仙品灵草",
		Reward:      achievementReward{Spirit: 10000, HerbRate: 1.5},
	},
	{
		Category:    "collection",
		ID:          "collection_10",
		Name:        "灵草大师",
		Description: "收集所有种类灵草",
		Reward:      achievementReward{Spirit: 3000, HerbRate: 1.2},
	},
	{
		Category:    "resources",
		ID:          "resources_1",
		Name:        "初获灵石",
		Description: "获得首枚灵石",
		Reward:      achievementReward{Spirit: 100},
	},
	{
		Category:    "resources",
		ID:          "resources_2",
		Name:        "小有积蓄",
		Description: "灵石数量达到1000",
		Reward:      achievementReward{Spirit: 1000},
	},
	{
		Category:    "resources",
		ID:          "resources_3",
		Name:        "灵石新人",
		Description: "灵石数量达到5000",
		Reward:      achievementReward{Spirit: 2000},
	},
	{
		Category:    "resources",
		ID:          "resources_4",
		Name:        "富甲一方",
		Description: "灵石数量达到10000",
		Reward:      achievementReward{Spirit: 5000},
	},
	{
		Category:    "resources",
		ID:          "resources_5",
		Name:        "灵石达人",
		Description: "灵石数量达到50000",
		Reward:      achievementReward{Spirit: 10000},
	},
	{
		Category:    "resources",
		ID:          "resources_6",
		Name:        "富可敌国",
		Description: "灵石数量达到100000",
		Reward:      achievementReward{Spirit: 20000, SpiritRate: 1.3},
	},
	{
		Category:    "resources",
		ID:          "resources_7",
		Name:        "灵石大师",
		Description: "灵石数量达到500000",
		Reward:      achievementReward{Spirit: 10000, SpiritRate: 1.5},
	},
	{
		Category:    "resources",
		ID:          "resources_8",
		Name:        "坐拥灵山",
		Description: "灵石数量达到1000000",
		Reward:      achievementReward{Spirit: 100000, SpiritRate: 2},
	},
	{
		Category:    "resources",
		ID:          "resources_9",
		Name:        "灵石传奇",
		Description: "灵石数量达到5000000",
		Reward:      achievementReward{Spirit: 30000, SpiritRate: 2.3},
	},
	{
		Category:    "resources",
		ID:          "resources_10",
		Name:        "灵石之神",
		Description: "灵石数量达到10000000",
		Reward:      achievementReward{Spirit: 100000, SpiritRate: 2.5},
	},
	{
		Category:    "alchemy",
		ID:          "alchemy_1",
		Name:        "初识丹道",
		Description: "首次成功炼制丹药",
		Reward:      achievementReward{Spirit: 200},
	},
	{
		Category:    "alchemy",
		ID:          "alchemy_2",
		Name:        "炼丹学徒",
		Description: "成功炼制5颗丹药",
		Reward:      achievementReward{Spirit: 500},
	},
	{
		Category:    "alchemy",
		ID:          "alchemy_3",
		Name:        "丹道小成",
		Description: "成功炼制10颗丹药",
		Reward:      achievementReward{Spirit: 1000},
	},
	{
		Category:    "alchemy",
		ID:          "alchemy_4",
		Name:        "炼丹达人",
		Description: "成功炼制50颗丹药",
		Reward:      achievementReward{Spirit: 2000},
	},
	{
		Category:    "alchemy",
		ID:          "alchemy_5",
		Name:        "丹道精通",
		Description: "成功炼制100颗丹药",
		Reward:      achievementReward{Spirit: 5000, AlchemyRate: 1.2},
	},
	{
		Category:    "alchemy",
		ID:          "alchemy_6",
		Name:        "炼丹大师",
		Description: "成功炼制500颗丹药",
		Reward:      achievementReward{Spirit: 10000, AlchemyRate: 1.3},
	},
	{
		Category:    "alchemy",
		ID:          "alchemy_7",
		Name:        "丹道宗师",
		Description: "炼制1000颗丹药",
		Reward:      achievementReward{Spirit: 50000, AlchemyRate: 2},
	},
	{
		Category:    "alchemy",
		ID:          "alchemy_8",
		Name:        "丹道之神",
		Description: "炼制10000颗丹药",
		Reward:      achievementReward{Spirit: 50000, AlchemyRate: 2.5},
	},
	{
		Category:    "alchemy",
		ID:          "alchemy_9",
		Name:        "丹道大师",
		Description: "获得所有丹方",
		Reward:      achievementReward{Spirit: 10000, AlchemyRate: 1.5},
	},
	{
		Category:    "alchemy",
		ID:          "alchemy_10",
		Name:        "仙丹炼师",
		Description: "炼制100颗仙品丹药",
		Reward:      achievementReward{Spirit: 30000, AlchemyRate: 1.5},
	},
}
